### ISSUE TITLE
不能分页查询错误日志 报错不够完善 LogDashboard版本号1.4.6 ABP.vNext 4.1.1

### ISSUE THREAD

**Issue by xuanhe168** [ShiWei-L/NlogDashboard#67]
卡住了?
![preview](https://user-images.githubusercontent.com/37821420/115171727-47af4580-a0f6-11eb-8a7d-6c062229cc0f.PNG)

刷新之后可以看到异常:
![exception](https://user-images.githubusercontent.com/37821420/115171768-5d246f80-a0f6-11eb-8774-e1045341426c.PNG)

详细错误:

Logger | Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware
-- | --
消息 | An unhandled exception has occurred while executing the request.

堆栈信息
System.NullReferenceException: Object reference not set to an instance of an object.
   at LogDashboard.Handle.DashboardHandle`1.GetPageResult(SearchLogInput input)
   at LogDashboard.Handle.DashboardHandle`1.SearchLog(SearchLogInput input)
   at LogDashboard.LogDashboardMiddleware.InvokeAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Volo.Abp.AspNetCore.Serilog.AbpSerilogMiddleware.InvokeAsync(HttpContext context. RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Volo.Abp.AspNetCore.Auditing.AbpAuditingMiddleware.InvokeAsync(HttpContext context. RequestDelegate next)
   at Volo.Abp.AspNetCore.Auditing.AbpAuditingMiddleware.InvokeAsync(HttpContext context. RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext. ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context. IEndpointRouter router. IUserSession session. IEventService events. IBackChannelLogoutService backChannelLogoutService)
   at IdentityServer4.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context. IAuthenticationSchemeProvider schemes)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at Volo.Abp.AspNetCore.Uow.AbpUnitOfWorkMiddleware.InvokeAsync(HttpContext context. RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Volo.Abp.AspNetCore.ExceptionHandling.AbpExceptionHandlingMiddleware.InvokeAsync(HttpContext context. RequestDelegate next)
   at Volo.Abp.AspNetCore.ExceptionHandling.AbpExceptionHandlingMiddleware.InvokeAsync(HttpContext context. RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Volo.Abp.AspNetCore.MultiTenancy.MultiTenancyMiddleware.InvokeAsync(HttpContext context. RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Builder.ApplicationBuilderAbpJwtTokenMiddlewareExtension.<>c__DisplayClass0_0.<<UseJwtTokenMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Volo.Abp.AspNetCore.Tracing.AbpCorrelationIdMiddleware.InvokeAsync(HttpContext context. RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.RequestLocalization.AbpRequestLocalizationMiddleware.InvokeAsync(HttpContext context. RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by realLiangshiwei** [comment]
Please try again

**Comment by xuanhe168** [comment]
这次更加严重 不但分页看不了刷新后点击详情也无效了

ABP.vNext版本
![企业微信截图_20210426160753](https://user-images.githubusercontent.com/37821420/116051643-6344be00-a6ab-11eb-907e-fc8f301ced95.png)

Acme.BookStore.Web模块依赖信息
![企业微信截图_20210426162312](https://user-images.githubusercontent.com/37821420/116052002-ccc4cc80-a6ab-11eb-9dea-b6ac6753f5d4.png)


运行后Logdashboard界面
![企业微信截图_20210426161416](https://user-images.githubusercontent.com/37821420/116051788-8a02f480-a6ab-11eb-8483-0410649f3297.png)

日志文件
[logs.log](https://github.com/realLiangshiwei/LogDashboard/files/6375405/logs.log)

**Comment by mingyouzhu** [comment]
Acme.BookStore.Web模块依赖信息
![企业微信截图_20210426162312](https://user-images.githubusercontent.com/37821420/116051914-b6b70c00-a6ab-11eb-92ad-0b5d88897154.png)
